use crate::dsl::{Slide, SlideType, Component};

pub async fn create_plan(topic: String) -> Vec<Slide> {
    vec![
        Slide {
            slide_type: SlideType::Cover,
            title: topic,
            components: vec![],
        },
        Slide {
            slide_type: SlideType::Summary,
            title: "Generated by AI Planner".into(),
            components: vec![Component::Text("Semantic DSL pipeline".into())],
        }
    ]
}
